; Press 'help' key (<f1>, C-h) to run help command, and b to see global key translations.

; When typing a key-chord that is a prefix command, enter '?' or '<f1>'
; to open buffer of key translations of that prefix command.
; When typing a prefix command, type '?' or '<f1>' to open buffer with
; available commands of that prefix.

; Key Mapping ;
; Remapping key inputs to other Elisp symbols.
; "C-i" returns "<tab>".
; To use real "C-i", use "<C-i>"
(bind-key-any input-decode-map [?\C-i] [C-i])
(bind-key-any input-decode-map [?\M-i] [M-i])
(bind-key-any input-decode-map [?\C-m] [C-m])
(bind-key-any input-decode-map [?\C-\M-i] [C-M-i])
; Key Mapping (End) ;

; Key Unbindings ;
;(global-unset-key [?\C-@])
(bind-key-global "C-SPC" 'space-times-2)
;(unbind-key-global "<ESC>"); prefix-command
(unbind-key-global "<insert>"); overwrite-mode
(unbind-key-global "<deletechar>"); overwrite-mode
(unbind-key-global "<home>"); move-beginning-of-line
(unbind-key-global "<end>"); move-end-of-line
(unbind-key-global "<prior>"); scroll-down-command
(unbind-key-global "<next>"); scroll-up-command
;(global-unset-key [tab])
(unbind-key-global "<f3>")
(unbind-key-global "<f4>")
(unbind-key-global "<f5>")
(unbind-key-global "<f6>")
(unbind-key-global "<f7>")
(unbind-key-global "<f8>")
(unbind-key-global "<f9>")
(unbind-key-global "<f10>")
;(unbind-key-global "<f11>")
(unbind-key-global "C--")
(unbind-key-global "C-q")
(unbind-key-global "M-q")
(unbind-key-global "C-w")
(unbind-key-global "M-w")
(unbind-key-global "C-e")
(unbind-key-global "M-e")
(unbind-key-global "M-r")
(unbind-key-global "C-t")
(unbind-key-global "M-t")
(unbind-key-global "C-y")
(unbind-key-global "M-y")
(unbind-key-global "C-u")
(unbind-key-global "M-u")
(unbind-key-global "C-o")
(unbind-key-global "M-o")
(unbind-key-global "C-p")
(unbind-key-global "M-a")
(unbind-key-global "M-d")
(unbind-key-global "<C-M-d>")
(unbind-key-global "C-f")
(unbind-key-global "M-f")
(unbind-key-global "C-g")
(unbind-key-global "C-h")
(unbind-key-global "M-h")
(unbind-key-global "C-j")
(unbind-key-global "M-j")
(unbind-key-global "C-M-j")
(unbind-key-global "C-k")
(unbind-key-global "M-k")
(unbind-key-global "C-M-k")
(unbind-key-global "C-l")
(unbind-key-global "M-l")
(unbind-key-global "C-;")
(unbind-key-global "M-;")
(unbind-key-global "C-z")
(unbind-key-global "M-z")
(unbind-key-global "M-c")
(unbind-key-global "C-b")
(unbind-key-global "M-b")
(unbind-key-global "M-m")
(unbind-key-global "M-,")
(unbind-key-global "M-.")
(unbind-key-global "M-/")
; Key Unbindings (End) ;

; Key Bindings ;
(bind-key-global "<f12>" 'term)
(bind-key-global "C-<f12>" 'term-char-mode)
(bind-key-global "M-<f12>" 'term-line-mode)
(bind-key-global "C--" '(lambda () "" (interactive) (text-scale-set (- text-scale-mode-amount 1))))
(bind-key-global "C-=" '(lambda () "" (interactive) (text-scale-set (+ text-scale-mode-amount 1))))
(bind-key-global "<kp-subtract>" '(lambda () "" (interactive) (text-scale-set (- text-scale-mode-amount 1))))
(bind-key-global "<kp-add>" '(lambda () "" (interactive) (text-scale-set (+ text-scale-mode-amount 1))))
; Frame Prefix
(bind-key-global "C-q s" 'save-buffers-kill-terminal)
(bind-key-global "C-q d" 'suspend-emacs)
; Window Prefix
(bind-key-global "C-w w" 'ace-window)
(bind-key-global "C-w t 1" '(lambda () "Inline lambda" '(interactive) (safe-enable-theme 'deeper-blue)))
(bind-key-global "C-w t 2" '(lambda () "Inline lambda" '(interactive) (safe-enable-theme 'misterioso)))
(bind-key-global "C-w t 3" '(lambda () "Inline lambda" '(interactive) (safe-enable-theme 'whiteboard)))
(bind-key-global "C-w i" 'decrease-window-size)
(bind-key-global "C-w o" 'find-file)
(bind-key-global "C-w d" 'delete-window)
(bind-key-global "C-w j" 'split-window-vertically)
(bind-key-global "C-w C-j" 'move-previous-window)
(bind-key-global "C-w k" 'split-window-horizontally)
(bind-key-global "C-w C-k" 'move-next-window)
(bind-key-global "C-w l" 'decrease-window-size-horizontally)
(bind-key-global "C-w ;" 'increase-window-size-horizontally)
(bind-key-global "C-w n" 'increase-window-size)
(bind-key-global "M-w o" 'find-file-other-window)
; Buffer Prefix
(bind-key-global "C-e = 1" '(lambda () "" '(interactive) (text-scale-set -4)))
(bind-key-global "C-e = 2" '(lambda () "" '(interactive) (text-scale-set -2)))
(bind-key-global "C-e = 3" '(lambda () "" '(interactive) (text-scale-set 0)))
(bind-key-global "C-e = 4" '(lambda () "" '(interactive) (text-scale-set 2)))
(bind-key-global "C-e = 5" '(lambda () "" '(interactive) (text-scale-set 4)))
(bind-key-global "C-e e" 'list-buffers)
(bind-key-global "C-e r" 'rename-buffer)
(bind-key-global "C-e u" 'undo)
(bind-key-global "C-e C-u" 'undo-tree-visualize)
(bind-key-global "C-e i" 'scroll-down-command)
(bind-key-global "C-e o" 'switch-to-buffer)
(bind-key-global "C-e s" 'save-buffer)
(bind-key-global "C-e C-s" 'save-some-buffers)
(bind-key-global "C-e d" 'kill-buffer)
(bind-key-global "C-e C-d" 'kill-buffer-and-window)
(bind-key-global "C-e n" 'scroll-up-command)
(bind-key-global "<C-i>" 'previous-line)
(bind-key-global "<M-i>" 'scroll-down-command)
(bind-key-global "<C-M-i>" 'beginning-of-buffer)
(bind-key-global "C-p" 'recenter-top-bottom)
(bind-key-global "C-a" 'universal-argument)
(bind-key-global "C-s" 'set-mark-command)
(bind-key-global "C-D" 'delete-forward-char)
(bind-key-global "M-d" 'kill-region)
(bind-key-global "C-f w" 'avy-goto-word-0)
(bind-key-global "C-f C-w" 'avy-goto-word-1)
(bind-key-global "C-f C-r" 'replace-string)
(bind-key-global "C-f f" 'isearch-forward)
(bind-key-global "C-f c" 'avy-goto-char)
(bind-key-global "C-f C-c" 'avy-goto-char-2)
(bind-key-global "C-f l" 'goto-line)
(bind-key-global "C-f C-l" 'avy-goto-line)
(bind-key-global "C-j" 'backward-char)
(bind-key-global "M-j" 'backward-word)
(bind-key-global "C-k" 'forward-char)
(bind-key-global "M-k" 'forward-word)
(bind-key-global "C-l" 'move-beginning-of-line)
(bind-key-global "M-l" 'backward-sentence)
(bind-key-global "C-;" 'move-end-of-line)
(bind-key-global "M-;" 'forward-sentence)
(bind-key-global "C-z" 'keyboard-quit)
(bind-key-global "C-c" 'kill-ring-save)
(bind-key-global "C-v" 'yank)
(bind-key-global "M-v" 'yank-pop)
(bind-key-global "C-n" 'next-line)
(bind-key-global "M-n" 'scroll-up-command)
(bind-key-global "C-M-n" 'end-of-buffer)
(bind-key-global "<C-m> a b b r" 'abbrev-mode)
(bind-key-global "<C-m> c s s" 'css-mode)
(bind-key-global "<C-m> a d" 'auto-dim-other-buffers-mode)
(bind-key-global "<C-m> m a g i t" 'magit-status)
(bind-key-global "<C-m> h t m l" 'html-mode)
(bind-key-global "<C-m> a i" 'aggressive-indent-mode)
(bind-key-global "<C-m> j s" 'javascript-mode)
(bind-key-global "<C-m> e l" 'emacs-lisp-mode)
(bind-key-global "<C-m> m a r k d o w n" 'markdown-mode)
(bind-key-global "<C-m> n e w" 'highlight-changes-mode)
(bind-key-global "<C-m> t e x t" 'text-mode)
(bind-key-global "<C-m> ?" 'describe-mode)
(bind-key-global "C-," 'unindent-region)
(bind-key-global "C-." 'indent-relative)
; Key Bindings (End) ;
